version: "latest"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: kuznetsov-v-g-netology-prometheus
    command: --web.enable-lifecycle --config.file=/home/vitaliy/REPOS/Docker/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
   # - prometheus-data:/prometheus
   pushgateway:
    job_name: 'kuznetsov-v-g-netology-pushgateway'
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
networks:
  kuznetsov-my-netology-hw:
  # ipv4_address: back-tier #10.0.2.16
#networks:
#  kuznetsov-my-netology-hw:
#    ipam:
#      config:
#        - subnet: 10.5.0.0/16
